version: "3.0"
services:
  redis:
    image: redis:3.2.0
  dockerapp:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
 
